#!/usr/bin/env node
/**
 * Mirror ADRs from the sibling `meta/adr/` repo into
 * `docs/architecture-decisions/` so the autogenerated sidebar surfaces them
 * as an "Architecture Decisions" section.
 *
 * Runs as a prebuild / prestart hook. The destination is regenerated on every
 * run and is gitignored — the source of truth stays in `meta/`.
 */

const fs = require('node:fs');
const path = require('node:path');

const SRC = path.resolve(__dirname, '..', '..', 'meta', 'adr');
const DEST = path.resolve(__dirname, '..', 'docs', 'architecture-decisions');

const CATEGORY = {
  label: 'Architecture Decisions',
  position: 5,
  collapsible: true,
  collapsed: true,
  link: {
    type: 'generated-index',
    description:
      'Architecture Decision Records, mirrored from meta/adr/. Each entry follows the Context / Decision / Consequences format.',
  },
};

function rmrf(target) {
  if (fs.existsSync(target)) {
    fs.rmSync(target, {recursive: true, force: true});
  }
}

function main() {
  rmrf(DEST);
  fs.mkdirSync(DEST, {recursive: true});

  fs.writeFileSync(
    path.join(DEST, '_category_.json'),
    JSON.stringify(CATEGORY, null, 2) + '\n',
  );

  if (!fs.existsSync(SRC)) {
    console.warn(
      `[sync-adrs] source ${SRC} not found — skipping (architecture-decisions section will be empty)`,
    );
    return;
  }

  const entries = fs
    .readdirSync(SRC)
    .filter((name) => name.endsWith('.md'))
    .sort();

  for (const name of entries) {
    fs.copyFileSync(path.join(SRC, name), path.join(DEST, name));
  }

  console.log(`[sync-adrs] mirrored ${entries.length} ADR(s) into ${DEST}`);
}

main();
